# Generated by Django 4.1.7 on 2023-07-16 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivementName', models.CharField(max_length=255, verbose_name='Achievement Name')),
                ('achivementType', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=255)),
                ('meritType', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeName', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('G', 'G')], max_length=2, verbose_name='Grade Name')),
                ('gradeScore', models.CharField(choices=[('90', '90'), ('80', '80'), ('75', '75'), ('70', '70'), ('66', '66'), ('60', '60'), ('50', '50'), ('46', '46'), ('40', '40'), ('20', '20')], max_length=2, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteName', models.CharField(max_length=255, verbose_name='Institute Name')),
                ('instituteDescription', models.TextField(verbose_name='Institute Description')),
                ('instituteLink', models.URLField(verbose_name='Institute Link')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=255, verbose_name='Subject Name')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('studentMerit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(max_length=255, verbose_name='Program Name')),
                ('programDescription', models.TextField()),
                ('programGrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.grade')),
                ('programInstitute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.institute')),
                ('programSubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.subject')),
            ],
        ),
    ]
