# Generated by Django 4.1.7 on 2023-07-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='programDescription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.grade', verbose_name='Grade Minimum Requirement'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programInstitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programSubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentProfile.subject', verbose_name='Subject Required'),
        ),
    ]
